### PR TITLE
[2/2] Collect BOSH-deployed service logs

### PR DESCRIPTION
**Pull request by adamstegman**
https://www.pivotaltracker.com/story/show/114329931

Collect all BOSH logs and send them to Sumo Logic. Allows configuration of source details so we can tag logs appropriately.

Also added an integration test! :sparkles:

### CODE REVIEW

**Comment by jeremiemv** [comment]
All checks have failed :(

**Comment by adamstegman** [comment]
Working out the kinks

**Comment by jeremiemv** [comment]
:bomb: :+1:

**Comment by jeremiemv** [comment]
:sheep: :it:

**Comment by ptg180** [comment]
:ship:

**Pull request merged**
