### PR TITLE
[2/2] Use the correct PID

### PR DESCRIPTION
**Pull request by adamstegman**
The console command forks a process that is then orphaned if the console is killed. So updates can never complete because killing the console PID does not actually kill the collector.

Using start also forks a process but immediately returns so we can grab the PID and put it in the pidfile.

### CODE REVIEW

**Comment by jeremiemv** [comment]
Is the the reason ``monit`` was choking up?

**Comment by jeremiemv** [comment]
:shipit:

**Comment by adamstegman** [comment]
Yeah this makes updates hang and never complete successfully without manual intervention. :worried:

**Comment by stuartparmenter** [comment]
:rocket:

**Pull request merged**
